name: Release

on:
  workflow_run:
    workflows: ["Validation"]
    types:
      - completed

permissions:
  contents: write
  id-token: write

jobs:
  release:
    if: >-
      ${ { github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' } }
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true
      - name: Checkout code at validated commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then npm ci; else npm install; fi
      - name: Build
        run: |
          if npm run | grep -q "build"; then npm run build; else echo "No build script"; fi
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.event.workflow_run.head_branch, 'main')
        with:
          tag_name: v${{ github.run_number }}
          name: Automated Release ${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
